titlePesanTiket = '//*[@id="accordion"]/div[1]'
sAwal = '//*[@id="select2-origination2-container"]'
txStasiunAwal = '//*[@class="select2-search__field"]'
pilihStasiun = '//*[@class="select2-results__option select2-results__option--highlighted"]'
sAkhir =  '//*[@id="select2-destination2-container"]'
txStasiunAkhir = '//*[@class="select2-search__field"]'
tanggalBerangkat = '//*[@id="departure_dateh2"]'
pilihTgl = '//*[@id="ui-datepicker-div"]/table/tbody/tr[5]/td[6]/a'
buttonCariKereta = '//*[@id="submittrain"]'
hasil = '//*[@class="top-cols"]/div[1]'